'use client';

interface BlogImageProps {
	image: {
		id: string | null;
		url: string | null;
		alt: string | null;
		position: number;
	};
}

export default function BlogImage({ image }: BlogImageProps) {
	if (!image.url) return null;

	// The alt field is the accessible description, not a caption. It is often
	// autogenerated ("Image 1"), so it is never rendered as visible text.
	return (
		<div className="my-4 overflow-hidden rounded-2xl border border-line bg-paper-2">
			{/* Post images are arbitrary remote CMS URLs. */}
			<img
				src={image.url}
				alt={image.alt || ''}
				className="h-auto w-full object-cover"
			/>
		</div>
	);
}
